### # ---------------------------------------------------
### # CONFIGURE OUR EX SWITCH INSIDE OF MIST
### # ---------------------------------------------------
- name: "build the YAML file with Jinja2 based on variables in the switch_config.yml file"
  template:
    src: switch_config.j2
    dest: tmp/switch_config.yml

- name: "store the file's contents as a variable named switch_config"
  set_fact:
    switch_config_raw: "{{ lookup('file','tmp/switch_config.yml') }}"

# ### A little explanation is needed here. There are times when loading a file's contents
# ###   in the way that we did in the previous task, the content will be rendered as a string
# ###   instead of the YAML dictionary we are hoping for. 
# ###   This task uses a little logic to account for these situations, forcing a load as a dictionary.
- name: "store switch_config_raw as switch_config, providing a translation if needed"
  set_fact:
    switch_config: "{{ switch_config_raw if switch_config_raw is mapping else switch_config_raw | from_yaml }}"

- name: "print the variable as yaml to the screen"
  debug:
    msg: "{{ switch_config }}"

- name: "print the variable as json to the screen"
  debug:
    msg: "{{ switch_config | to_json }}"

- name: "configure the switch through the Mist REST API"
  uri:
    url: "{{ mist.base_url }}/sites/{{ mist.site_id }}/devices/{{ mist.device_id }}"
    method: PUT
    return_content: false
    status_code: "200"
    headers:
      Content-Type: "application/json"
      Authorization: "Token {{ mist.token }}"
    body: "{{ switch_config | to_json }}"
    force_basic_auth: yes
