### # ---------------------------------------------------
### # RETRIEVE INTERFACES FROM DEVICES
### # ---------------------------------------------------
- name: "Retrieves interfaces from a device from Netbox"
  uri:
    url: "https://{{ netbox.base_url }}/dcim/interfaces/?device={{ item.name }}"
    method: GET
    return_content: yes
    status_code: "200"
    headers:
      Content-Type: "application/json"
      Authorization: "Token {{ netbox.token }}"
    force_basic_auth: yes
    validate_certs: false
  loop: "{{ switches }}"
  register: interfaces

- debug:
    msg: "{{ interfaces }}"
